### PR TITLE
Fix duplicate entries bug

### LINKED ISSUE #81: Fix duplicate entries in address book bug

### PR DESCRIPTION
**Pull request by clarissatjx**
Fixes #81

### CODE REVIEW

File: src/main/java/seedu/address/storage/JsonSerializableAddressBook.java [hunk 1]
```diff
@@ -83,14 +82,6 @@ public AddressBook toModelType() throws IllegalValueException {
             addressBook.addOwner(owner);
         }
 
-        for (JsonAdaptedOwner jsonAdaptedOwner : owners) {
-            Owner owner = jsonAdaptedOwner.toModelType();
-            if (addressBook.hasOwner(owner)) {
-                throw new IllegalValueException(MESSAGE_DUPLICATE_OWNER);
-            }
-            addressBook.addOwner(owner);
-        }
```
Comment (jloh02) [inline src/main/java/seedu/address/storage/JsonSerializableAddressBook.java:92]: Thanks for removing this unnecessary duplication of code!

**Review by jloh02 — APPROVED** [review]
