### PR TITLE
Fix index bug

### LINKED ISSUE #167: Alpha bug: Linking to owner 0 results in index out of bounds error
Using the link command with "o0" results in out of bounds error.
Screenshot 2024-11-07 at 4 02 41 PM
Screenshot 2024-11-07 at 4 03 04 PM

### PR DESCRIPTION
**Pull request by naythee169**
Fixes #167 and #170

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -18,6 +18,7 @@
 public class ParserUtil {
 
     public static final String MESSAGE_INVALID_INDEX = "Index is not a non-zero unsigned integer.";
+    public static final String MESSAGE_INVALID_INPUT = "Input is not of the correct format.";
```
Comment (jloh02) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:21]: Perhaps this can be more descriptive?

**Review by jloh02 — CHANGES_REQUESTED** [review]

**Review by jloh02 — APPROVED** [review]
